#!/bin/sh

# prints the current volume or 🔇 if muted.

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e pulsemixer ;;
	2) pamixer -t ;;
	4) pamixer --allow-boost -i 1 ;;
	5) pamixer --allow-boost -d 1 ;;
	3) notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.
- Scroll to change." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

VOL="$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{if ($3 == "[MUTED]") {print 0} else {print $2 * 100}}')"

# if muted, print 🔇 and exit.
if [ "$VOL" -le 0 ]; then echo ﱝ && exit; fi

if      [ "$VOL" -gt 66 ]; then ICON=""; \
elif    [ "$VOL" -gt 33 ]; then ICON=""; \
else    ICON=""; fi

echo "$ICON $VOL%"
