#!/bin/sh

# prints the current volume or 🔇 if muted.

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e pulsemixer ;;
	2) pamixer -t ;;
	4) pamixer --allow-boost -i 1 ;;
	5) pamixer --allow-boost -d 1 ;;
	3) notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.
- Scroll to change." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

VOL="$(amixer sget Master | awk '/Left:/ {print substr($5, 2, length($5) - 3)}')"
TOGGLE="$(amixer sget Master | awk '/Left:/ {print substr($6, 2, length($6) - 2)}')" # 'off' for muted

# if muted, print 🔇 and exit.
if [ "$TOGGLE" = "off" ] || [ "$VOL" = 0 ]; then echo ﱝ && exit; fi

if      [ "$VOL" -gt 66 ]; then ICON=""; \
elif    [ "$VOL" -gt 33 ]; then ICON=""; \
else    ICON=""; fi

echo "$ICON $VOL%"
